name: zain_mobiles
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.5.0
  custom_navigation_bar: ^0.8.2
  dot_curved_bottom_nav: ^0.0.2
  firebase_core: ^3.7.0
  flutter:
    sdk: flutter

  fluttertoast: ^8.2.8
  google_fonts: 
  provider: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/